#!/usr/bin/env bash

# sends files to remotre server over scp
if [[ $# -lt 3 ]]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  #scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":/home/"$3"
fi
