#!/usr/bin/env bash
# install nginx web-server

sudo apt-get update
sudo apt-get -y install nginx
sudo rm /var/www/html/*.html && touch /var/www/html/index.html
echo "Hello World!" >> /var/www/html/index.html
sudo service nginx start
