#!/usr/bin/env bash
# install nginx web-server

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
