#!/usr/bin/env bash
# displays `To infinity and beyond` indefinitely
# sleep 2 between each iteration
# displays `I am invincible!!!` when recieving a SIGTERM signal

trap 'echo "I am invincible!!!"'
while true; do
	echo "To infinity and beyond"
	sleep 2
done
